version: dev # Version placeholder (overridden by workflow)
markdown: kramdown
style: gmamaladzecv

repository: gmamaladze/george-mamaladze-cv
baseurl: /george-mamaladze-cv

include:
  - css/

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - README.md
  - tmp/
  - vendor/