markdown: kramdown
style: gmamaladzecv

# Repository configuration
repository: gmamaladze/george-mamaladze-cv
baseurl: /george-mamaladze-cv

# Include media files
include:
  - media/

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - DOCKER_PREVIEW.md
  - README.md
  - tmp/
  - vendor/
  - cv/
  - cv.md