# Version placeholder (overridden by workflow)
version: dev
markdown: kramdown
style: gmamaladzecv

# Repository configuration
repository: gmamaladze/george-mamaladze-cv
baseurl: /george-mamaladze-cv

# Include CSS files
include:
  - css/

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - README.md
  - tmp/