name: Build CV (HTML & PDF)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggers

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Read version from file
      run: |
        VERSION=$(cat version)
        echo "VERSION=$VERSION" > version.env
        echo "Read version: $VERSION"
      shell: bash

    # Build Jekyll site so Pages serves processed HTML (with layouts & CSS)
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true

    - name: Install Jekyll dependencies
      run: |
        bundle install

    - name: Load version env
      run: |
        echo "Loading version from version.env"
        cat version.env
      shell: bash
    - name: Build Jekyll site with version
      run: |
        source version.env
        echo "version: $VERSION" > _config_version.yml
        bundle exec jekyll build --trace --config _config.yml,_config_version.yml
      shell: bash
      
    - name: Install wkhtmltopdf (PDF generator)
      run: |
        sudo apt-get install -y wkhtmltopdf
          
    - name: Convert HTML to PDF (via wkhtmltopdf)
      run: |
        # Convert Jekyll-built HTML to PDF with wkhtmltopdf
        ls -la _site/index.html
        wkhtmltopdf \
          --page-size A4 \
          --margin-top 0.75in \
          --margin-right 0.75in \
          --margin-bottom 0.75in \
          --margin-left 0.75in \
          --encoding UTF-8 \
          --enable-local-file-access \
          --disable-smart-shrinking \
          --no-stop-slow-scripts \
          --javascript-delay 1000 \
          file://$(pwd)/_site/index.html "George Mamaladze CV.pdf"
          
    - name: Upload PDF artifact
      uses: actions/upload-artifact@v4
      with:
        name: cv-pdf
        path: "George Mamaladze CV.pdf"
        retention-days: 90
        
    - name: Setup Pages (if main branch)
      if: github.ref == 'refs/heads/main'
      uses: actions/configure-pages@v4
      
    - name: Upload to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site
        
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    
    permissions:
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4